### ISSUE TITLE
Support for Babylon.js?

### ISSUE THREAD

**Issue by raoneel** [swift502/Sketchbook#14]
Hey, this project is awesome! Thanks for building it. I was wondering if you had any plans to port this to other platforms such as [Babylon](https://www.babylonjs.com/). It seems to support all of the features from three.js you are using and would love to use it there.

**Comment by swift502** [comment]
Thanks!

I'm not even sure what Babylon is exactly. If there was a benefit to porting this project then.. maybe?
But this project is so dynamic I really don't think it's ready to get ported to anything. New stuff I'm working on in the dev branch breaks pretty much all compatibility with the currect master version. 😄
I also use my fork of Cannon, so that'd have to get transferred to Babylon. I have no idea how the physics plugins work.

If there was a clear benefit then I'd consider it. I'm quite happy with the project as it is now running on three js.

**Comment by raoneel** [comment]
Makes sense, thanks. Did you modify Cannon physics specifically for this project?

**Comment by swift502** [comment]
Yes. Just a few small, but significant changes. I would've been happy to contribute to Cannon, but the owner abandoned it years ago and so now we have [372 Cannon forks](https://github.com/schteppe/cannon.js/network/members) because people can't contribute.

I think it's a shame.
