### ISSUE TITLE
awesome job!

### ISSUE THREAD

**Issue by radziksh** [swift502/Sketchbook#2]
you did an awesome job! I will try to move my pet project to your platform :) will try to show the results soon :)

**Comment by radziksh** [comment]
![screenshot_1](https://user-images.githubusercontent.com/1275228/53678328-97401680-3cce-11e9-85f5-7e89657298aa.png)

it works! :)

**Comment by swift502** [comment]
looks awesome 😄 
If you needed help with something let me know. Currently I'm working on implementing vehicles, and once thats done, making the character be able to punch or shoot to actually interact with the environment.

Seeing that you're interested is really motivating though, thanks.

Also, activate windows. 😃

**Comment by radziksh** [comment]
@swift502 just motivation message, based on your SDK  https://rajab.dev not finished, but I'm slowly moving towards the goal :)

**Comment by swift502** [comment]
@radziksh That's awesome! Great skin texture replacement. 😄 

A few notes:

- I like how the character moves from side to side when running around. Have you moved the center of rotation (tilting) up a bit to achieve this? Or is it just a coincidence?
- The physics objects move around in a jerky way when you slow down time. You know you can use CANNON.Body's interpolatedPosition and interpolatedQuaternion instead of position and quaternion for smoother movement right?
- Did you use Blender for the graphics? Some of the object faces seem to be inverted. You can fix that with Shift+N or Alt+N and Flip faces when in Blender. (Unless it's intentional of course. And unless you're not using Blender at all. :) )

Other than that, it's very cool, thanks for letting me know 🙂
I just finished helicopter physics. Hopefully I'll do more vehicles soon.
https://youtu.be/vAkx1-wYurY
