### ISSUE TITLE
how about making a react-three version?

### ISSUE THREAD

**Issue by amir-al-razin** [swift502/Sketchbook#40]

**Comment by barhatsor** [comment]
Why React tho?

**Comment by swift502** [comment]
I probably won't because I deem Sketchbook to be finished at this point. All the features I cared about are present.
And ironically I'm not a big expert on web dev. So I have no clue what it would bring to the project or what would it look like.

Bottom line is I'm unfortunately not that interested in extending Sketchbook any further. And a huge change which restructures (even if the code becomes cleaner and nicer) isn't something I'll probably want to merge at this point. But you can fork it and extend it however you like obviously.

@jeremy-coleman did some work on Sketchbook tidying it up, maybe he would know if getting react-three would be worthwhile.
